# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68af9eb8c06331656a2be6d4b4c8c29940a2bbe6907d968897e011b56bc23207bf6958e9bcd2358353576cb79786e76322ad1c6b90276bf0f4da5e79004231d

test:
  secret_key_base: 35e215219cf44b3554772394e97fcedfcc1047df83825feaeb9e06de2f72d1eb2e94e6b819ad80dac1b9871251d144253dea846049aeccff3516e21d1c6c8ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
